API_KEY = "SUA_API_KEY_TESTNET"
API_SECRET = "SEU_API_SECRET_TESTNET"

TRADING_PAIRS = ["BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "ADAUSDT"]
TIMEFRAMES = ["1m", "5m", "15m"]  

# Estratégia
STOP_LOSS_ATR_MULTIPLIER = 1.5
TAKE_PROFIT_ATR_MULTIPLIER = 3
RISK_PERCENT = 1.0
MAX_DAILY_LOSS_PERCENT = 5.0

# Telegram alerts
TELEGRAM_TOKEN = ""
TELEGRAM_CHAT_ID = ""

# Binance Testnet URL
BASE_URL = "https://testnet.binancefuture.com"
